language: objective-c
osx_image: xcode7.2

before_install:
	- brew update
	- brew outdated xctool || brew upgrade xctool

script: xctool	-workspace Patchr.xcworkspace \
-scheme Patchr \
-sdk iphonesimulator \
-destination 'name=iPhone 6 Plus' \
test -resetSimulator
